[profile.default]
src = "contracts"
out = "out"
test = "tests/integration"
libs = ["lib", ".venv/lib/python3.12/site-packages"]

[vyper]
# You need vyper to be in your PATH environment
# variable for this to work
path = "vyper"
