name: testing
on: [push]

jobs:
  unitary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.vvm
          key: compiler-cache-${{ hashFiles('**/poetry.lock') }}

      - name: Setup Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Tests
        run: python -m pytest tests/unitary -n auto
