name: testing
on: [push]

jobs:
  unitary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.vvm
          key: compiler-cache-${{ hashFiles('**/poetry.lock') }}

      - name: Setup Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install Requirements
        run: poetry install --group dev

      - name: Run Tests
        run: python -m pytest tests/unitary -n auto
